spring:
  application:
    title: My Application Title
    description: My Application Description
    name: my-service
    cloud:
      config:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/security_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
